Airport.find_or_create_by(city: 'San Francisco', name: 'San Francisco International Airport')
Airport.find_or_create_by(city: 'New York', name: 'John F. Kennedy International Airport')
Airport.find_or_create_by(city: 'Los Angeles', name: 'Los Angeles International Airport')
Airport.find_or_create_by(city: 'Chicago', name: 'Chicago Midway International Airport')
Airport.find_or_create_by(city: 'Houston', name: 'George Bush Intercontinental Airport')
Airport.find_or_create_by(city: 'Miami', name: 'Miami International Airport')
Airport.find_or_create_by(city: 'Dallas', name: 'Dallas/Fort Worth International Airport')
Airport.find_or_create_by(city: 'Philadelphia', name: 'Philadelphia International Airport')
Airport.find_or_create_by(city: 'Washington', name: 'Dulles International Airport')
Airport.find_or_create_by(city: 'Boston', name: 'Boston Logan International Airport')
Airport.find_or_create_by(city: 'Santiago', name: 'Arturo Merino Benitez International Airport')
Airport.find_or_create_by(city: 'Sao Paulo', name: 'Allan Gray International Airport')
Airport.find_or_create_by(city: 'Buenos Aires', name: 'Ministro Pistarini International Airport')
Airport.find_or_create_by(city: 'Brasilia', name: 'Tancredo Neves International Airport')
Airport.find_or_create_by(city: 'Lima', name: 'Jorge Chávez International Airport')
Airport.find_or_create_by(city: 'Sydney', name: 'Kingsford Smith International Airport')
Airport.find_or_create_by(city: 'Melbourne', name: 'Melbourne International Airport')
Airport.find_or_create_by(city: 'Perth', name: 'Perth International Airport')
Airport.find_or_create_by(city: 'Canberra', name: 'Canberra International Airport')
Airport.find_or_create_by(city: 'Brisbane', name: 'Brisbane International Airport')

